### ISSUE TITLE
Channels integration testing

### ISSUE THREAD

**Issue by moliva** [decentraland/dservices#18]
Ticket for tracking issues related to the channels feature. Please add the issue description below in a bullet.

- [x] fix: `joinChannel` returns an error when it shouldn't -> remove incorrect validation.
- [x] feat: add `onChannelMembership()` listener to handle `joinChannel` and `leaveChannel` correctly.
- [x] fix: the interfaces `getChannelMembers` and  `joinOrCreateChannel` are missing in `BrowserInterface`.
- [x] fix: the interface `muteErrorChannel` is missing in `IUnityInterface`.
- [x] fix: `getJoinedChannels` retrieves an empty list.
- [x] fix: `getChannelInfo` panics -> typo in `getChannelInfoPayload`.
- [x] fix: `getChannelMessages` always retrieves the last messages -> typo in `getChannelMessagesPayload`.
- [x] fix: the `leaveChannel` action is not being dispatched.
- [x] feat: send `updateTotalUnseenMessages` when leaving channel.
- [x] fix: the handler for sending channel messages is missing.
- [x] fix: send the right `messageType` and `recipient` value when `onMessage()` -> both values depend on the messageType.
- [x] fix: send `updateTotalUnseenMessagesByChannel` when `onMessage()` -> remove unnecessary validation.

**Comment by Julieta11** [comment]
All the listed issues were addressed in the PR: [fix: channels feature integration](https://github.com/decentraland/kernel/pull/557).
