### ISSUE TITLE
Integration work and test plan running

### ISSUE THREAD

**Issue by moliva** [decentraland/dservices#34]
- [x] Find a solution for lack of uniqueness in the `friendRequestId` -> [problem and posible solution](https://github.com/decentraland/kernel/pull/803)

- [x] When renderer calls `GetFriendRequests` immediately after receiving  the `ReceiveFriendRequest` message, the body of that request is empty. [PR](https://github.com/decentraland/kernel/pull/803)

- [ ] The message sent in the request should not only be part of the message history, but it should also trigger a notification of a new message when the request is accepted, similar to LinkedIn.

- [ ] The event filter from matrix is not working as expected. We are not correctly filtering out* events and this is a problem because we are sending empty messages from events like delete or with empty state keys as part of the message history. [PR](https://github.com/decentraland/matrix-client/pull/117)

**Comment by Julieta11** [comment]
[Test cases and good-to-know flows](https://www.notion.so/decentraland/RFC-Technical-Assessment-New-Friend-Request-24e8259c26544df68c1f715edbb1b896#f1d3d000b26f4fb4b207ded487c70e04)

**Comment by Julieta11** [comment]
Issues found by QA will be reported [in the PR](https://github.com/decentraland/unity-renderer/pull/3779), unless there are a lot, in which case they will be moved into an Excel.

**Comment by Julieta11** [comment]
The last two items of the list have a specific ticket -> [link](https://app.zenhub.com/workspaces/workstream-social--identity-63a59f6982704e0037c63c29/issues/gh/decentraland/matrix-client/115)
