### ISSUE TITLE
Prepare Wearables/Emotes/Names/Lands lambdas for pagination

### ISSUE THREAD

**Issue by sandrade-dcl** [decentraland/dservices#43]
We currently have these 4 lambdas for obtaining data related to NFTs:

**Werables**:
```
https://peer.decentraland.org/lambdas/nfts/wearables/{userId}?pageSize={pageSize}&pageNum={pageNum}
```
**Emotes**:
```
https://peer.decentraland.org/lambdas/nfts/emotes/{userId}?pageSize={pageSize}&pageNum={pageNum}
```
**Names**:
```
https://peer.decentraland.org/lambdas/nfts/names/{userId}?pageSize={pageSize}&pageNum={pageNum}
```
**Lands**:
```
https://peer.decentraland.org/lambdas/nfts/lands/{userId}?pageSize={pageSize}&pageNum={pageNum}
```

Only the first one (wearables lambdas) is returning us the field `totalAmount` that is needed to be able to implement a correct pagination in the renderer's UIs, the other 3 ones are missing this field.

We need all of them to include the `totalAmount` field.

**More context**: https://decentralandteam.slack.com/archives/C04D6A48XSN/p1673983987557929

**Comment by manumena** [comment]
I think we are going to need some help from the dapps team to get the total amount of an nft through a query to theGraph. Right now the only way to know how many of an nft a user owns is to make a query for all of them, which we are trying to avoid since the main feature of these endpoints is that they are paginated.
Follow the discussion here: https://decentralandteam.slack.com/archives/C022B026W1F/p1674152333320849

**Comment by manumena** [comment]
Our current options to solve this from lambdas side:
- When the first page is requested: make an extra request to theGraph for the whole amount of the nft to count them (it would be a query for only one field to minimize the payload) in parallel with querying the data for the page. The total amount would be returned only for the first page in this way, and it would add some delay to it.
- Query for the whole amount of the nft and cached it in memory, as it is with the wearables. We want to avoid this for the commitment it represents in the long run, for example adding more data to the response would increment the size of the cache which could lead to an overflow. Also would have some more delay in the response, even more than in the first option.
- Querying theGraph for only the total amount of the nft, which requires a previous work from dapps team which involves adding complexity to the subgraph. More details in the previous comment's link
